name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      # Install dependencies
      - run: npm ci

      # Build and output webpack stats
      - run: npm run build -- --json webpack-stats.json

      # Save artifacts/webpack-stats.json to use on relative-ci.yaml
      - name: Upload RelativeCI artifacts
        uses: relative-ci/agent-upload-artifact-action@5385e83369baff03c39115fa512e9f3bed0248de
        with:
          webpackStatsFile: ./webpack-stats.json
