name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      # Install dependencies
      - run: npm ci

      # Build and output webpack stats to artifacts/webpack-stats.json
      - run: npm run build --if-present

      # Save artifacts/webpack-stats.json to use on relative-ci.yaml
      - name: Upload workflow artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts
