name: RelativeCI

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2

      - name: Send webpack stats to RelativeCI
        uses: relative-ci/agent-action@07d2d4af800e7f4b49932689b33c5abc57e7775e
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          key: ${{ secrets.RELATIVE_CI_KEY }}
