name: RelativeCI

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - uses: hmarr/debug-action@v2

      - name: Send webpack stats to RelativeCI
        uses: relative-ci/agent-action@workflow-run-support
        with:
          webpackStatsFile: ./webpack-stats.json
          artifactName: 'artifacts'
          key: ${{ secrets.RELATIVE_CI_KEY }}
          debug: true
