name: RelativeCI

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send webpack stats to RelativeCI
        uses: relative-ci/agent-action@6fc8ea737b6eb3ff2938d2c465a0d4a329897b97
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          key: ${{ secrets.RELATIVE_CI_KEY }}
