name: RelativeCI

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send webpack stats to RelativeCI
        uses: relative-ci/agent-action@12ae70ae754dd23b097fc19af712a45b8426de55
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          key: ${{ secrets.RELATIVE_CI_KEY }}
