name: RelativeCI

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2

      - name: Send webpack stats to RelativeCI
        uses: relative-ci/agent-action@181004aa365ac96e2c469e693908e59ceca3a367
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          key: ${{ secrets.RELATIVE_CI_KEY }}
